// Original pentatonic camp band. Audio is scheduled only after a user gesture.
export function createSoundscape(isMuted, Context) {
  let ctx=null,master=null,music=null,fx=null,nextBeat=0,step=0,pull=null,noise=null,wasPlaying=false,zoneAt=-99;
  const melody=[74,null,78,81,78,null,76,74,71,null,74,76,78,76,74,null,74,78,81,null,83,81,78,76,74,null,71,69,71,74,null,null];
  const hz=n=>440*Math.pow(2,(n-69)/12);
  function ensure(){if(isMuted())return false;try{if(!ctx){const C=Context||window.AudioContext||window.webkitAudioContext;if(!C)return false;ctx=new C();master=ctx.createGain();master.gain.value=.85;const limiter=ctx.createDynamicsCompressor();limiter.threshold.value=-18;limiter.ratio.value=5;master.connect(limiter);limiter.connect(ctx.destination);music=ctx.createGain();music.gain.value=.32;music.connect(master);fx=ctx.createGain();fx.gain.value=.62;fx.connect(master);noise=ctx.createBuffer(1,ctx.sampleRate,ctx.sampleRate);const a=noise.getChannelData(0);let x=0,seed=9281;for(let i=0;i<a.length;i++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;x=(x+((seed/4294967296)*2-1)*.1)/1.04;a[i]=x*2;}nextBeat=ctx.currentTime+.06;}if(ctx.state==='suspended')ctx.resume().catch(()=>{});return true}catch{return false}}
  function note(midi,time,dur=.18,gain=.13,bus=fx,type='triangle',slide=null){if(!ctx||isMuted())return;const o=ctx.createOscillator(),env=ctx.createGain(),filter=ctx.createBiquadFilter();o.type=type;o.frequency.setValueAtTime(hz(midi),time);if(slide!==null)o.frequency.exponentialRampToValueAtTime(hz(slide),time+dur);filter.type='lowpass';filter.frequency.value=type==='triangle'?2100:3100;env.gain.setValueAtTime(0,time);env.gain.linearRampToValueAtTime(gain,time+.006);env.gain.exponentialRampToValueAtTime(.0001,time+dur);o.connect(filter);filter.connect(env);env.connect(bus);o.start(time);o.stop(time+dur+.02)}
  function rustle(time,dur=.08,gain=.15,frequency=1500){if(!ctx||isMuted())return;const src=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),env=ctx.createGain();src.buffer=noise;filter.type='bandpass';filter.frequency.value=frequency;filter.Q.value=.8;env.gain.setValueAtTime(gain,time);env.gain.exponentialRampToValueAtTime(.0001,time+dur);src.connect(filter);filter.connect(env);env.connect(fx);src.start(time);src.stop(time+dur+.01)}
  function stopPull(){if(!pull)return;const t=ctx.currentTime;pull.env.gain.cancelScheduledValues(t);pull.env.gain.setTargetAtTime(.0001,t,.018);pull.osc.stop(t+.1);pull.wobble.stop(t+.1);pull.src.stop(t+.1);pull=null;}
  function beginPull(){if(!ensure())return;stopPull();const t=ctx.currentTime,o=ctx.createOscillator(),env=ctx.createGain(),w=ctx.createOscillator(),wg=ctx.createGain(),src=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),ng=ctx.createGain();o.type='sine';o.frequency.value=125;env.gain.value=.001;env.gain.setTargetAtTime(.08,t,.05);w.frequency.value=5;wg.gain.value=3;w.connect(wg);wg.connect(o.frequency);o.connect(env);env.connect(fx);src.buffer=noise;src.loop=true;filter.type='lowpass';filter.frequency.value=700;ng.gain.value=.035;src.connect(filter);filter.connect(ng);ng.connect(env);o.start(t);w.start(t);src.start(t);pull={osc:o,env,wobble:w,vibrato:wg,src,noiseGain:ng};}
  function event(kind,streak=0){if(!ensure())return;const t=ctx.currentTime;stopPull();music.gain.cancelScheduledValues(t);music.gain.setValueAtTime(.12,t);music.gain.linearRampToValueAtTime(.32,t+.6);
    if(kind==='start'){[74,78,81].forEach((n,i)=>note(n,t+i*.085,.16,.12));}
    else if(kind==='rebound'){note(66,t,.27,.16,fx,'sine',45);note(45,t+.09,.15,.09,fx,'sine',66);}
    else if(kind==='good'||kind==='perfect'){rustle(t,.10,.14,2600);note(81,t,.14,.17,fx,'triangle',50);note(48,t+.16,.12,.2,fx,'sine',36);rustle(t+.16,.05,.23,700);const phrase=kind==='perfect'?[74,78,81,86]:[74,81];phrase.forEach((n,i)=>note(n,t+.2+i*.07,.19,.15));if(kind==='perfect'){[0,.035,.065].forEach((delay,i)=>note(66+i*3,t+.22+delay,.2,.07,fx,'sine',81+i*2));}if(streak>2)note(86,t+.49,.24,.08);}
    else if(kind==='short'||kind==='over'){note(kind==='over'?81:71,t,.24,.16,fx,'sine',42);rustle(t+.15,.07,.13,600);[66,62,57].forEach((n,i)=>note(n,t+.24+i*.11,.2,.12));}
    else if(kind==='clear'){[74,78,81,86,83,86].forEach((n,i)=>note(n,t+i*.11,.3,.15));}
    else if(kind==='end'){[74,71,69].forEach((n,i)=>note(n,t+i*.14,.24,.1));}
  }
  function update({state,holding=false,power=0,bow=null}){if(!ctx)return;const t=ctx.currentTime;const playing=state==='play'&&!isMuted();master.gain.setTargetAtTime(isMuted()?0:.85,t,.03);
    if(playing&&!wasPlaying){nextBeat=t+.04;step=0;}if(!playing){nextBeat=t+.04;if(pull)stopPull();}wasPlaying=playing;
    if(playing){if(nextBeat<t-.15)nextBeat=t+.04;let count=0;while(nextBeat<t+.12&&count++<8){const i=step%32,cycle=Math.floor(step/32)%3,n=melody[i];if(n!==null)note(n+(cycle===2&&i>=16?-12:0),nextBeat,.16,.21,music);if(i%4===0){note(i%8===0?50:45,nextBeat,.25,.25,music,'sine');note(38,nextBeat,.09,.12,music,'sine',26);}if(i%2===1)note(91,nextBeat,.04,.08,music,'triangle');if(cycle===1&&i%4===2)note(62,nextBeat,.13,.075,music);nextBeat+=60/116/2;step++;}}
    if(pull&&holding){pull.osc.frequency.setTargetAtTime(125+power*2.1,t,.035);pull.vibrato.gain.setTargetAtTime(2+power*.055,t,.03);pull.noiseGain.gain.setTargetAtTime(.03+power*.0008,t,.03);if(bow&&power>=bow.perfectMin&&power<=bow.perfectMax&&t-zoneAt>.65){note(86,t,.11,.08);zoneAt=t;}}
    else if(pull)stopPull();
  }
  function mute(){if(!ctx)return;stopPull();master.gain.setTargetAtTime(isMuted()?0:.85,ctx.currentTime,.02);}
  function dispose(){stopPull();if(ctx)ctx.close();ctx=null;}
  return {ensure,beginPull,stopPull,event,update,mute,dispose,info:()=>({ready:!!ctx,state:ctx?.state||'unavailable',scheduledSteps:step,pulling:!!pull})};
}
