import { DURATION, GOAL, rankFor, TYPES, makeBow, makeDraw, advanceDraw, judge, points, titleFor, seedNumber, isAim, zoneAt, targetState, flightTime, maximumScore, mastery } from './engine.mjs?v=crowd-clear-1';
import { RANKS, HECKLES, createCrowdPicker, imperialReport, TALES, REVIVE_RIDDLES } from './content.mjs?v=crowd-clear-1';
import { drawScene, text, line } from './scene.mjs?v=crowd-clear-1';
import { createSoundscape } from './audio.mjs';
const $ = id => document.getElementById(id);
const pickCrowd=createCrowdPicker();
const C = $('scene'), ctx = C.getContext('2d');
const INK='#292b23', PAPER='#f2e9d6', RED='#b43d2f', GOLD='#e5b63c';
const storage={get(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},set(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}};
const query=new URLSearchParams(location.search);
const sharedSeed=/^[a-z0-9-]{1,32}$/.test(query.get('challenge')||'')?query.get('challenge'):null;
const friendCleared=/^\d{1,2}$/.test(query.get('cleared')||'')?Math.min(GOAL,Number(query.get('cleared'))):null;
const friendFrom=Number(query.get('from'))||0;
const friendScore=/^\d{1,6}$/.test(query.get('score')||'')?Number(query.get('score')):null;
const dailySeed='d-'+new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()).replaceAll('-','');
const S={state:'home',mode:'normal',seed:'',score:0,hits:0,perfects:0,streak:0,bestStreak:0,lives:3,elapsed:0,holding:false,phase:0,bow:null,draw:makeDraw(),outcome:null,outcomeAge:0,miss:null,started:false,muted:storage.get('kg-v3-muted',true),result:null};
S.reviveUsed=false;S.reviveQuestion=null;S.volley=0;S.startFrom=0;S.timed=false;
let last=performance.now(), pointer=null, posterURL=null, idleT=0;
const band=createSoundscape(()=>S.muted);
function ensureAudio(){return band.ensure();}
function setSound(){ $('sound').textContent=S.muted?'静':'音';$('sound').setAttribute('aria-label',S.muted?'开启音乐与音效':'关闭音乐与音效');$('sound').setAttribute('aria-pressed',String(!S.muted)); }
$('sound').onclick=()=>{S.muted=!S.muted;storage.set('kg-v3-muted',S.muted);if(!S.muted)ensureAudio();band.mute();setSound();if(!S.muted)band.event('start');};setSound();
function setVisible(play){$('home').hidden=play;$('home-actions').hidden=play;$('hud').hidden=!play;$('expedition').hidden=!play;$('controls').hidden=!play;$('bow-tag').hidden=!play;$('combo').hidden=!play;$('scene-caption').hidden=play;$('app').classList.toggle('playing',play)}
function home(){$('revive').hidden=true;band.stopPull();S.state='home';S.holding=false;pointer=null;$('result').hidden=true;$('pause').hidden=true;setVisible(false);$('speech').textContent=sharedSeed?'有人叫你来比一箭。':'你说你能开？';$('feedback').innerHTML='';$('feedback').className='feedback';$('draw').classList.remove('holding');$('scene').setAttribute('aria-label','小豆丁抱着弓，小伙伴在场边围观。');if(!sharedSeed){const cp=storage.get('kg-v6-checkpoint',0);$('start').firstChild.textContent=cp?`继续第 ${cp+1} 关 `:'闯五十关 ';}if(sharedSeed){$('start').firstChild.textContent='接招，开一局 ';$('home-copy').textContent=friendScore!==null?`朋友这局 ${friendScore} 分。同一弓序，同样难度，你来试试。`:'同一弓序，同样难度。来比谁的手稳。'} }
function start(mode='normal',seed=null,from=null){ensureAudio();band.event('start');S.state='play';S.reviveUsed=false;S.mode=mode;S.seed=seed||(mode==='daily'?dailySeed:'r-'+Math.floor(Math.random()*0xffffffff).toString(36));Object.assign(S,{misses:0,volleyScore:0,crowdWords:null,crowdUntil:0,score:0,hits:0,perfects:0,streak:0,bestStreak:0,lives:3,elapsed:0,holding:false,phase:0,outcome:null,outcomeAge:0,miss:null,started:false,result:null});S.timed=mode==='daily'||mode==='sprint'||mode==='challenge'&&query.get('rules')==='sprint';S.startFrom=mode==='normal'?(from??storage.get('kg-v6-checkpoint',0)):0;S.startFrom=Math.max(0,Math.min(GOAL-5,Math.floor(S.startFrom/5)*5));S.hits=S.startFrom;S.volley=0;$('result').hidden=true;$('pause').hidden=true;$('poster-preview').hidden=true;$('share-status').textContent='';setVisible(true);nextBow();updateHUD();window.scrollTo(0,0);last=performance.now();$('draw').focus({preventScroll:true});}
function nextBow(){S.bow=makeBow(S.hits,S.seed);S.draw=makeDraw();S.draw.arrow=S.volley;S.shot=null;S.outcome=null;S.outcomeAge=0;S.phase=0;$('feedback').innerHTML='';$('feedback').className='feedback';$('draw').disabled=false;$('draw').classList.remove('holding');$('draw').firstChild.textContent='按住拉弓 ';$('draw').lastElementChild.textContent='松手出箭';$('bow-type').textContent=TYPES[S.bow.type];$('bow-name').textContent=S.bow.bowName;$('good-zone').style.left=S.bow.min+'%';$('good-zone').style.width=(S.bow.max-S.bow.min)+'%';$('perfect-zone').style.left=S.bow.perfectMin+'%';$('perfect-zone').style.width=(S.bow.perfectMax-S.bow.perfectMin)+'%';const hints={mounted:'抓住马步平稳的瞬间放箭。',soft:'红区松手就中，金区神射。',stubborn:'回扯一次后继续拉，别慌。',shaky:'力道会抖，看准再松手。',wind:'逆风忽强忽弱，别只凭节奏。',moving:'靶在上下跑，红区也会移动。',willow:'瞄着柳叶松手，窗口很窄。',volley:`连续中${S.bow.required}箭才过关 · 已中 ${S.volley}/${S.bow.required}`};$('speech').textContent=S.hits===GOAL-1?'最后大比：连续三箭，才能封帅。':hints[S.bow.type];$('instruction').textContent=`${S.bow.chapterName} · ${S.bow.distance}步 · ${S.bow.mounted?'骑射':S.bow.moving?'移动靶':'站射'} · 连中${S.bow.required}箭过关`;$('bow-type').textContent=`第${S.bow.chapter+1}章 · ${TYPES[S.bow.type]}`;updatePower();}
function updateHUD(){$('score').textContent=S.score;$('time').textContent=S.timed?Math.ceil(Math.max(0,DURATION-S.elapsed)):`${S.hits}/${GOAL}`;document.querySelector('.clock small').textContent=S.timed?'秒':'已过关';document.querySelector('.clock').classList.toggle('urgent',S.timed&&DURATION-S.elapsed<=15);$('lives').textContent=Array.from({length:3},(_,i)=>i<S.lives?'◆':'◇').join(' ');$('lives').setAttribute('aria-label',`剩余${S.lives}次失手机会`);$('combo').querySelector('b').textContent=S.streak;$('earned-rank').textContent=rankFor(S.hits);$('rank-goal').textContent=S.hits>=GOAL?'三十关已过 · 大将军！':`第 ${S.hits+1} / ${GOAL} 弓 → ${S.bow.rank}`;$('road-fill').style.width=Math.min(100,S.hits/GOAL*100)+'%';}
function updatePower(){const z=zoneAt(S.bow,S.draw);$('good-zone').style.left=z.min+'%';$('good-zone').style.width=(z.max-z.min)+'%';$('perfect-zone').style.left=z.perfectMin+'%';$('perfect-zone').style.width=(z.perfectMax-z.perfectMin)+'%';const p=Math.min(100,S.draw.power);$('needle').style.left=p+'%';$('power').textContent=Math.round(p)+'%';$('meter').setAttribute('aria-valuenow',Math.round(p));$('scene').setAttribute('aria-label',`${S.bow.bowName}，${TYPES[S.bow.type]}，弓力${Math.round(p)}%，红区${Math.round(z.min)}到${Math.round(z.max)}，金区${Math.round(z.perfectMin)}到${Math.round(z.perfectMax)}。`);}
function hold(){if(S.state!=='play'||S.outcome||S.holding)return;ensureAudio();S.started=true;S.holding=true;$('draw').classList.add('holding');$('draw').firstChild.textContent='稳住… ';$('draw').lastElementChild.textContent='松手出箭';band.beginPull();}
function release(cancel=false){if(!S.holding)return;S.holding=false;$('draw').classList.remove('holding');if(cancel){band.stopPull();S.draw=makeDraw();S.draw.arrow=S.volley;updatePower();return}if(S.state!=='play'||S.outcome)return;resolveShot(judge(S.bow,S.draw.power,S.draw));}
function resolveShot(result){if(S.state!=='play'||S.outcome)return;S.holding=false;S.shot=result.impact||judge(S.bow,S.draw.power,S.draw).impact;S.outcome=result.kind;S.outcomeAge=0;$('draw').disabled=true;$('draw').classList.remove('holding');const hit=result.kind==='perfect'||result.kind==='good';band.event(result.kind,hit?S.streak+1:0);if(hit){S.streak++;S.bestStreak=Math.max(S.bestStreak,S.streak);const gain=points(result.kind,S.streak);S.score+=gain;S.volleyScore+=gain;S.volley++;const cleared=S.volley>=S.bow.required;if(cleared){S.hits++;S.volley=0;S.volleyScore=0;if(!S.timed&&S.hits%5===0){S.lives=3;if(S.mode==='normal')storage.set('kg-v6-checkpoint',S.hits>=GOAL?0:Math.max(storage.get('kg-v6-checkpoint',0),S.hits));}}if(result.kind==='perfect'){S.perfects++;$('speech').textContent=pickCrowd(!cleared&&S.volley%2===0?'volley':'perfect')}else $('speech').textContent=pickCrowd(cleared?'good':'volley');$('feedback').innerHTML=(result.kind==='perfect'?'神射！':'中了！')+`<small>${cleared?rankFor(S.hits):`连珠 ${S.volley}/${S.bow.required} · 尚未过关`} · +${gain} 分</small>`;$('feedback').className='feedback show '+result.kind;$('draw').firstChild.textContent='下一把弓 ';$('draw').lastElementChild.textContent='马上就来';}else{S.lives--;S.misses++;S.score=Math.max(0,S.score-S.volleyScore);S.volleyScore=0;S.streak=0;S.volley=0;S.miss=result.kind;const reason=result.kind==='short'?`箭落低了 · 力道还差 ${Math.ceil(result.gap)}%`:`箭越过了 · 力道多 ${Math.ceil(result.gap)}%`;$('feedback').textContent=reason;$('feedback').style.fontSize='26px';$('feedback').className='feedback show';$('speech').textContent=pickCrowd(result.kind);$('draw').firstChild.textContent=S.lives?'再来一箭 ':'收弓了 ';$('draw').lastElementChild.textContent=S.lives?'刚才的弓，再试一次':'看看战报';}S.crowdSpeaker=((S.crowdSpeaker??-1)+1+Math.floor(Math.random()*4))%5;S.crowdWords=$('speech').textContent;S.crowdUntil=idleT+4.5;S.crowdMood=result.kind;updateHUD();}
function offerRevive(){S.reviveUsed=true;S.state='revive';S.holding=false;pointer=null;band.stopPull();S.reviveQuestion=REVIVE_RIDDLES[seedNumber(S.seed+':revive:'+S.hits)%REVIVE_RIDDLES.length];$('revive').hidden=false;$('revive-question').textContent=S.reviveQuestion.q;$('revive-feedback').textContent='';$('revive-continue').hidden=true;$('revive-skip').hidden=false;$('revive-skip').textContent='不答了，收弓';$('revive-choices').replaceChildren();const shift=seedNumber(S.seed+':choices')%S.reviveQuestion.choices.length;for(let i=0;i<S.reviveQuestion.choices.length;i++){const j=(i+shift)%S.reviveQuestion.choices.length,b=document.createElement('button');b.textContent=S.reviveQuestion.choices[j];b.onclick=()=>answerRevive(j);$('revive-choices').append(b);}$('revive-choices').firstElementChild.focus();}
function answerRevive(index){if(S.state!=='revive')return;S.state='revive-answer';$('revive-choices').querySelectorAll('button').forEach(b=>b.disabled=true);const correct=index===S.reviveQuestion.answer;S.reviveCorrect=correct;$('revive-feedback').textContent=(correct?'答对了！补一次机会。':'答错了，这次收弓。')+' '+S.reviveQuestion.reveal;$('revive-continue').hidden=false;$('revive-continue').textContent=correct?'再给我一箭':'查看战报';$('revive-skip').hidden=true;$('revive-continue').focus();band.event(correct?'good':'short');}
$('revive-continue').onclick=()=>{if(S.state!=='revive-answer')return;$('revive').hidden=true;S.state='play';if(!S.reviveCorrect){finish('lives');return;}S.lives=1;S.volley=0;nextBow();updateHUD();last=performance.now();$('draw').focus({preventScroll:true});};
$('revive-skip').onclick=()=>{if(S.state!=='revive')return;$('revive').hidden=true;S.state='play';finish('lives');};
function finish(reason=S.hits>=GOAL?'clear':S.lives===0?'lives':'time'){if(S.state!=='play')return;S.state='result';band.event(reason==='clear'?'clear':'end');S.holding=false;pointer=null;$('controls').hidden=true;$('hud').hidden=true;$('expedition').hidden=true;$('home').hidden=true;$('home-actions').hidden=true;$('result').hidden=false;$('app').classList.remove('playing');$('feedback').style.fontSize='';const title=reason==='clear'?'大将军':`止步 · ${rankFor(S.hits)}`;
 const quote=S.hits>30?(S.hits>=GOAL?'全营起立，这次真服了。':'将军还在向前，下一箭见真章。'):TALES[Math.min(30,S.hits)];
 $('ending-reason').textContent=reason==='clear'?'五十关全过，大将军归位！':`${reason==='time'?'九十秒到了':'三次失手，收弓回营'} · 止步于${RANKS[Math.min(S.hits,GOAL-1)].title}关前`;
 const grade=mastery(S.score,S.startFrom,S.misses);$('mastery').textContent=reason==='clear'?`${S.startFrom?'本段 · ':''}${grade.label}\n距满分尚差 ${grade.gap} 分`:`本段满分 ${grade.top} · 尚待精进`;const decree=imperialReport({...S,reason,grade},rankFor(S.hits));S.result={...S,title,quote,reason,grade,decree};$('edict-heading').textContent=decree.heading;$('edict-grant').textContent=decree.grant;$('edict-citation').textContent=decree.citation;$('edict-reward').textContent=decree.reward;$('edict-seal').replaceChildren(...Array.from(decree.seal,c=>{const cell=document.createElement('span');cell.textContent=c;return cell;}));const artKind=reason==='clear'?(grade.gap===0&&S.startFrom===0&&S.misses===0?'supreme':'clear'):reason==='time'?'time':'retry';S.result.artKind=artKind;const dg=$('award-doodle').getContext('2d');dg.clearRect(0,0,240,145);drawAwardDoodle(dg,artKind);$('award-doodle').setAttribute('aria-label',({supreme:'戴小花庆祝的神射小豆丁',clear:'领鸡腿的小豆丁',time:'抱着时钟的小豆丁',retry:'抱着草靶继续练习的小豆丁'})[artKind]);$('result-title').textContent=decree.rank;$('result-score').textContent=S.score;$('result-hits').textContent=S.hits;$('result-perfect').textContent=S.perfects;$('result-streak').textContent=S.bestStreak;$('result-quote').textContent='御批：'+decree.verdict;$('result-mode').textContent=S.mode==='daily'?'今日怪弓 · '+S.seed.slice(2):S.mode==='challenge'?'同题挑战 · 战报':S.timed?'速挑战 · 九十秒':`闯关战报 · 第 ${S.startFrom+1} 关起步`;const k='kg-v6-50-best-'+(S.timed?'sprint':'campaign')+'-'+S.startFrom+'-'+(S.mode==='daily'?S.seed:'all'),best=storage.get(k,0);storage.set(k,Math.max(best,S.score));$('record').textContent=S.mode==='challenge'&&friendCleared!==null? (S.hits!==friendCleared?`你过了 ${S.hits} 关，朋友过了 ${friendCleared} 关。`:friendFrom!==S.startFrom?'官阶相同，起点不同，分数不作比较。':S.score>friendScore?`同官阶，你多 ${S.score-friendScore} 分。`:S.score===friendScore?'同官阶、同分，再比一局。':`同官阶，距朋友还差 ${friendScore-S.score} 分。`):S.mode==='challenge'&&friendScore!==null?(S.score>friendScore?`你比朋友多了 ${S.score-friendScore} 分。`:S.score===friendScore?'平手。谁再拉一局？':`距朋友还差 ${friendScore-S.score} 分。`):S.score>best?'刷新了你的校场纪录。':`你的${S.mode==='daily'?'今日':'个人'}最佳：${Math.max(best,S.score)} 分`;$('share-status').textContent='';window.scrollTo(0,0);$('again').focus({preventScroll:true});}
function challengeURL(){const u=new URL(location.href);u.search='';u.hash='';u.searchParams.set('challenge',S.seed);u.searchParams.set('score',S.score);u.searchParams.set('cleared',S.hits);u.searchParams.set('from',S.startFrom);u.searchParams.set('rules',S.timed?'sprint':'campaign');return u.href;}
function shareText(){return `我在《开弓》拿了 ${S.score} 分，${S.perfects} 次神射。${S.result.decree.grant}${S.result.decree.rank}。${S.result.decree.reward} 同一张弓，你来试试。`;}
$('challenge').onclick=async()=>{const url=challengeURL(),local=['localhost','127.0.0.1','::1'].includes(location.hostname);if(local){$('share-status').textContent='当前是本地预览。正式上线后，朋友才能从外网接招；现在可复制链接在本机验证。'}try{if(navigator.share&&!local){await navigator.share({title:'开弓｜来比一箭',text:shareText(),url});$('share-status').textContent='挑战已交给分享面板。';}else{await navigator.clipboard.writeText(shareText()+'\n'+url);$('share-status').textContent=local?'已复制本机挑战链接。正式上线后换成正式网址即可给朋友接招。':'挑战链接已复制。发给朋友，同题比手。';}}catch(e){if(e.name!=='AbortError'){$('share-status').replaceChildren(document.createTextNode('复制未成功，可长按或选中下面的链接：'));const a=document.createElement('a');a.href=url;a.textContent=url;$('share-status').append(document.createElement('br'),a);}}};
function drawAwardDoodle(g,kind){
 const ink='#82684b',red='#b66d55';g.save();g.lineWidth=2.6;g.strokeStyle=ink;g.fillStyle='#faf2df';g.lineCap='round';g.lineJoin='round';
 const stroke=(points)=>{g.beginPath();points.forEach(([x,y],i)=>i?g.lineTo(x,y):g.moveTo(x,y));g.stroke();};
 const oval=(x,y,rx,ry,fill='#faf2df')=>{g.beginPath();g.ellipse(x,y,rx,ry,0,0,Math.PI*2);g.fillStyle=fill;g.fill();g.stroke();};
 // A squat ink-drawn bean, with tiny feet and a loose kerchief.
 oval(115,104,23,20);oval(102,123,9,4);oval(130,123,9,4);oval(114,64,36,33);
 stroke([[108,32],[103,24],[114,29],[120,22]]);stroke([[81,53],[94,43],[131,39]]);oval(80,52,7,4,'#a7b5a0');stroke([[77,54],[69,64],[78,61]]);
 g.fillStyle=ink;for(const x of [103,123]){g.beginPath();g.arc(x,64,2,0,7);g.fill();}stroke([[111,75],[116,77],[120,74]]);g.strokeStyle='#d3a18b';stroke([[91,75],[98,75]]);stroke([[131,74],[137,74]]);g.strokeStyle=ink;
 if(kind==='supreme'){for(let i=0;i<5;i++){const a=i*Math.PI*2/5;oval(139+Math.cos(a)*7,29+Math.sin(a)*7,5,5,'#dba494');}oval(139,29,3,3,'#e6c879');stroke([[92,104],[75,91],[66,74]]);stroke([[135,102],[154,89],[163,72]]);for(const [x,y] of [[54,49],[180,46],[167,108]]){stroke([[x-5,y],[x+5,y]]);stroke([[x,y-5],[x,y+5]]);}}
 else if(kind==='clear'){stroke([[134,108],[156,90]]);oval(164,72,13,17,'#dcb590');stroke([[159,87],[153,100]]);oval(150,103,4,4);oval(156,106,4,4);stroke([[96,104],[85,95]]);}
 else if(kind==='time'){oval(165,100,19,22);stroke([[165,86],[165,100],[175,105]]);stroke([[157,75],[171,75]]);stroke([[137,107],[151,110]]);stroke([[94,107],[80,102]]);}
 else{oval(146,107,24,23,'#e5d6b7');oval(146,107,15,15);oval(146,107,5,5,'#c68269');stroke([[132,99],[140,104],[145,100]]);stroke([[91,104],[112,116],[125,116]]);stroke([[173,83],[187,76],[183,84]]);}
 stroke([[72,132],[161,132]]);g.restore();
}

function posterCanvas(){const p=document.createElement('canvas');p.width=1080;p.height=1440;const g=p.getContext('2d'),d=S.result.decree;g.fillStyle='#f5ecd5';g.fillRect(0,0,1080,1440);g.strokeStyle='#b49c6c';g.lineWidth=3;g.strokeRect(42,42,996,1356);g.strokeRect(56,56,968,1328);
 const center=(s,y,size,color=INK)=>{g.save();g.textAlign='center';text(g,s,540,y,size,color);g.restore()};
 const para=(s,y,size=30,color=INK)=>{let row='',n=0;g.font=`600 ${size}px system-ui`;for(const c of s){if(g.measureText(row+c).width>860){text(g,row,110,y+n*48,size,color);row=c;n++;}else row+=c;}if(row)text(g,row,110,y+n*48,size,color);return y+(n+1)*48;};
 center('奉 天 承 运 · 校 场 勘 绩',125,25,'#8c7956');center(d.heading,224,64,RED);center(d.grant+' · '+d.rank,328,68);center(S.result.grade.label,388,28,'#977647');line(g,110,430,970,430,'#c6b58f',2);
 let y=para(d.citation,495,31);y=para('御批：'+d.verdict,y+45,32,RED);y=para('恩赏：'+d.reward,y+35,29);
 g.save();g.translate(276,765);g.scale(2.2,2.2);drawAwardDoodle(g,S.result.artKind);g.restore();
 center(`${S.score} 分 / 本段满分 ${S.result.grade.top} 分`,1120,33);center(`距满分 ${S.result.grade.gap} 分 · ${S.startFrom?'续关战绩':'从头挑战'}`,1175,25,'#8c7956');center('钦 此',1270,47,RED);center('兵部校场司 録 · 御膳房会签',1330,24,'#8c7956');return p;}

$('poster').onclick=()=>{const p=posterCanvas();p.toBlob(blob=>{if(!blob){$('share-status').textContent='海报生成失败，请再试一次。';return}if(posterURL)URL.revokeObjectURL(posterURL);posterURL=URL.createObjectURL(blob);$('poster-preview').src=posterURL;$('poster-preview').hidden=false;const a=document.createElement('a');a.href=posterURL;a.download=`开弓战报-${S.score}.png`;a.click();$('share-status').textContent='战报已生成。若手机没有自动下载，可长按下方海报保存。';},'image/png');};
$('start').onclick=()=>start(sharedSeed?'challenge':'normal',sharedSeed);$('daily').onclick=()=>start('daily');$('sprint').onclick=()=>start('sprint');$('fresh').onclick=()=>start('normal',null,0);$('again').onclick=()=>start(S.mode,S.seed,S.startFrom);$('home-button').onclick=home;$('exit').onclick=()=>{release(true);home();};
$('draw').addEventListener('pointerdown',e=>{if(e.button!==0||S.state!=='play'||S.outcome)return;e.preventDefault();if(pointer!==null)return;pointer=e.pointerId;try{$('draw').setPointerCapture(e.pointerId)}catch{}hold();});
$('draw').addEventListener('pointerup',e=>{if(pointer!==e.pointerId)return;pointer=null;release();});$('draw').addEventListener('pointercancel',()=>{pointer=null;release(true)});$('draw').addEventListener('lostpointercapture',()=>{if(pointer!==null){pointer=null;release(true)}});
window.addEventListener('keydown',e=>{if(e.code!=='Space'||S.state!=='play'||e.target.closest('button')&&e.target!==$('draw'))return;e.preventDefault();if(!e.repeat)hold()});window.addEventListener('keyup',e=>{if(e.code==='Space'&&S.state==='play'){e.preventDefault();release()}});
function pause(){if(S.state!=='play')return;band.stopPull();release(true);pointer=null;S.state='paused';$('pause').hidden=false;$('draw').classList.remove('holding');}
window.addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});$('resume').onclick=()=>{S.state='play';$('pause').hidden=true;last=performance.now();$('draw').focus({preventScroll:true});};
function loop(now){const dt=Math.min(.05,Math.max(0,(now-last)/1000));last=now;idleT+=dt;if(S.state==='play'){if(S.started)S.elapsed+=dt;if(S.outcome){S.outcomeAge+=dt;if(S.outcomeAge>=Math.max(S.lives===0?1.1:.85,(S.shot?.flight||0)+.35)){if(S.lives===0&&!S.reviveUsed&&S.hits<GOAL){offerRevive();}else if(S.lives===0||S.hits>=GOAL)finish();else{if(S.outcome==='good'||S.outcome==='perfect')nextBow();else{const bow=S.bow;nextBow();S.bow=bow;$('feedback').style.fontSize='';}}}}else {const rebounded=advanceDraw(S.draw,S.bow,dt,S.holding);if(rebounded){$('speech').textContent='它咬一口而已，继续拉！';band.event('rebound');if(S.holding)band.beginPull()}if(S.holding&&S.draw.power>=102)resolveShot({kind:'over',gap:S.draw.power-zoneAt(S.bow,S.draw).max});updatePower();if(S.draw.power>=zoneAt(S.bow,S.draw).perfectMin&&S.draw.power<=zoneAt(S.bow,S.draw).perfectMax){$('draw').lastElementChild.textContent='金区！松手神射'}else if(S.draw.power>=zoneAt(S.bow,S.draw).min&&S.draw.power<=zoneAt(S.bow,S.draw).max){$('draw').lastElementChild.textContent='现在松手可中'}else if(S.draw.power>zoneAt(S.bow,S.draw).max){$('draw').lastElementChild.textContent='拉过了！'}}if(S.state==='play'&&S.timed&&S.elapsed>=DURATION)finish();updateHUD();}
 band.update({state:S.state,holding:S.holding,power:S.draw.power,bow:S.bow});
 $("sound").dataset.audioState=band.info().state;$("sound").dataset.audioSteps=band.info().scheduledSteps;
 drawScene(ctx,{power:S.state==='home'?15+Math.sin(idleT)*3:S.draw.power,t:idleT,outcome:S.state==='home'?null:S.outcome,age:S.outcomeAge,home:S.state==='home',hits:S.hits,bow:S.bow,draw:S.draw,volley:S.volley,shot:S.shot,speaker:S.crowdSpeaker,heckle:idleT<S.crowdUntil?S.crowdWords:null,crowdMood:idleT<S.crowdUntil?S.crowdMood:null,shapeScale:C.clientWidth&&C.clientHeight?C.clientWidth*720/(C.clientHeight*1000):1});requestAnimationFrame(loop);}
home();C.height=720;requestAnimationFrame(loop);
